src/pages/host/Management.tsx, src/pages/host/setAccommodations/AddAccommodations.tsx, src/pages/host/setAccommodations/HostDocuments.tsx, src/pages/host/setAccommodations/MultiAccommodations.tsx, src/pages/host/setAccommodations/MultiStaterRoom.tsx
=> CHORE : 폴더구조 생성

package-lock.json, package.json, src/App.tsx, src/assets/Chips.tsx, src/index.css, src/pages/Main.tsx, tailwind.config.js
=> DESIGN: 테일윈드 세팅 수정, ui chip생성중

src/App.tsx, src/assets/Chips.tsx, src/assets/buttons/Button.tsx, src/pages/Main.tsx, src/pages/search/index.tsx, tailwind.config.js
=> DESIGN: #64 ui버튼생성

src/assets/buttons/Button.tsx
=> DESIGN: ui타입지정

src/App.tsx, src/components/Popup.tsx
일단 제 생각대로 팝업 컴포넌트 구성해봤습니다. 추후 논의를 통해 변경 예정.
=> DESIGN: Popup 완성(수정 및 검토 필요)

src/components/Popup.tsx
=> DESIGN: popup css 수정

src/assets/Divider.tsx, src/assets/buttons/Button.tsx, src/assets/carousel/Arrow.tsx, src/assets/carousel/Carousel.tsx, src/assets/carousel/carouselStyle.css, src/components/DetailInfo.tsx, src/components/InfoTemp1.tsx, src/components/InfoTemp2.tsx, src/components/cards/CardRoom.tsx, src/components/cards/CardStateroom.tsx, src/index.css, src/layouts/Layout.tsx, src/pages/room/Accommodations.tsx
=> STYLE: 숙소 디테일

src/App.tsx, src/assets/carousel/Carousel.tsx, src/components/cards/CardAccommodations.tsx, src/pages/search/index.tsx
=> SYTLE:숙소 카드 제작

src/pages/room/Orders.tsx
=> STYLE : 예약 요청페이지

src/assets/Input.tsx, src/pages/user/EmailVerification.tsx
=> DESIGN/ 이메일 인증

src/components/CancelPopup.tsx, src/components/Popup.tsx
=> DESIGN: 예약취소팝업1 완료

src/App.tsx, src/pages/user/SignUpSuccessful.tsx
=> DESIGN/ 회원가입완료팝업#92

src/App.tsx, src/pages/user/WarningNotice.tsx
=> DESIGN/ 주의안내문구#94

src/App.tsx, src/pages/user/MembershipWithdrawal.tsx
=> DESIGN/ 회원탈퇴#41

src/App.tsx, src/assets/Badges.tsx, src/components/cards/CardMypage.tsx
=> DESIGN/ 마이페이지 카드#98

src/pages/search/Map.tsx
=> STYLE: 지도 수정

src/App.tsx, src/components/cards/CardMypage.tsx, src/pages/user/Mypage.tsx
=> DESIGN/ 마이페이지

src/App.tsx, src/assets/SegmentMenu.tsx, src/components/Popup.tsx, src/components/cards/CardOrderFix.tsx, src/components/cards/CardOrderWating.tsx, src/pages/host/Management.tsx
=> DESIGN : 호스트 예약관리

package-lock.json, package.json, src/App.tsx, src/components/Search.tsx
=> DESIGN/ 검색진행중#56

src/pages/reservations/AccmoInfoCard.tsx, src/pages/reservations/PaymentInfo.tsx, src/pages/reservations/isReservationComfirmed.tsx
=> DESIGN 예약대기 페이지 폰트 크기 수정

package-lock.json, src/App.tsx
=> CHORE: 라우트 변경

src/App.tsx, src/assets/Dropdown.tsx, src/components/Search.tsx
=> DESIGN/Feture/user search#56

package-lock 복사본.json
=> 공공 API 작업 전 백업

src/assets/Chips.tsx, src/pages/host/setAccommodations/OnlyStaterRoom.tsx, src/pages/host/setAccommodations/components/AccommodationUse.tsx
=> DESIGN : chip 인풋 추가

src/App.tsx, src/axios/accommodationApi.ts, src/axios/orderApi.ts, src/components/Filter.tsx, src/components/Search.tsx, src/pages/room/Accommodations.tsx, src/pages/search/index.tsx, src/stores/useAccommodationsStore.tsx, src/stores/useStateroomStore.tsx
=> FEATL: 주스탠드 상태 관리

src/axios/client.ts, src/axios/userApi.ts, src/pages/user/SignIn.tsx
=> FEAT/로그인 #139

package-lock.json, src/App.tsx, src/components/Popup.tsx, src/pages/host/Management.tsx, src/pages/host/hostCalender/HostAccommoList.tsx, src/pages/host/managementAPI/DeleteAPI.tsx, src/stores/usePopupStore.tsx
=> REFACTOR: 호스트 메인, 팝업 컴포넌트  리펙토링 및 버그 수정

src/axios/client.ts, src/stores/workspace.code-workspace
=> FEAT/client수정 #139

src/axios/client.ts
=> FEAT:aixos 헤더 설정

src/axios/client.ts, src/components/Popup.tsx, src/pages/host/HostMain.tsx, src/pages/host/Management.tsx, src/pages/host/hostCalender/HostAccommoList.tsx
=> CHORE: Client.tsx 임시 복구

src/axios/client.ts, src/axios/orderApi.ts, src/axios/roomApi.ts, src/components/DetailInfo.tsx, src/components/InfoTemp2.tsx, src/components/cards/CardMain.tsx, src/components/cards/CardStateroom.tsx, src/customHooks/useDateDashFormet.tsx, src/customHooks/useDateDotFormet.tsx, src/customHooks/useErrorImage.tsx, src/customHooks/useTimeFormet.tsx, src/pages/Main.tsx, src/pages/room/Accommodations.tsx, src/pages/room/Orders.tsx, src/pages/room/Stateroom.tsx, src/pages/search/Map.tsx, src/stores/useAccommodationsStore.tsx, src/stores/useStateroomStore.tsx
=> FEAT: 숙소/객실 디테일 불러오는 값 수정

src/assets/Badges.tsx, src/axios/client.ts, src/axios/orderApi.ts, src/components/InfoTemp2.tsx, src/components/cards/CardMypage.tsx, src/pages/room/Orders.tsx, src/pages/user/Mypage.tsx, src/stores/useAccommodationsStore.tsx, src/stores/useAuthStore.tsx, src/stores/useStateroomStore.tsx
=> FEAT: mypage 이용 카드리스트

src/axios/orderApi.ts, src/components/DetailInfo.tsx, src/components/cards/CardStateroom.tsx, src/pages/room/Stateroom.tsx
FIX : 충돌해결
stateroom파일에서 stay_type 받아오는 값이 빠져서 에러납니다.
=> FIX : 충돌해결

src/assets/Badges.tsx, src/assets/Header.tsx, src/axios/client.ts, src/components/cards/CardStateroom.tsx, src/pages/Main.tsx, src/pages/host/index.tsx, src/pages/reservations/index.tsx, src/pages/room/Orders.tsx, src/pages/search/index.tsx, src/pages/user/Mypage.tsx, src/pages/user/index.tsx
FEAT : HEADER 마이페이지/로그인/로그아웃 상태따라 페이지 이동
=> FEAT : HEADER 마이페이지/로그인/로그아웃 상태따라 페이지 이동

src/axios/client.ts, src/axios/userApi.ts, src/pages/user/SignUp.tsx
=> FEAT/회원가입/클라이언트 유저타입 수정#162

src/App.tsx, src/assets/Badges.tsx, src/axios/orderApi.ts, src/components/CheckInOut.tsx, src/components/cards/CardMypage.tsx, src/customHooks/useDateDotFormet.tsx, src/pages/reservations/AccmoInfoCard.tsx, src/pages/reservations/GuestInfo.tsx, src/pages/reservations/PaymentInfo.tsx, src/pages/reservations/ReservAccoCard.tsx, src/pages/reservations/ReservationCompleted.tsx, src/pages/room/Orders.tsx, src/pages/user/Mypage.tsx
=> FEAT : 숙소 예약완료 디테일

src/axios/searchApi.tsx, src/components/Search.tsx, src/components/cards/CardAccommodations.tsx, src/components/cards/CardMain.tsx, src/customHooks/usePriceFormet.tsx, src/pages/Main.tsx, src/pages/reservations/AccmoInfoCard.tsx, src/pages/reservations/PaymentInfo.tsx, src/pages/reservations/ReservationCompleted.tsx, src/pages/room/Accommodations.tsx, src/pages/room/Orders.tsx, src/pages/room/Stateroom.tsx, src/pages/search/index.tsx, src/stores/useSearchStore.tsx, src/stores/useStateroomStore.tsx
=> FEAT: 검색 정보 불러오기

src/axios/client.ts, src/axios/userApi.ts, src/pages/host/setAccommodations/StructureType.tsx, src/pages/user/SignOut.tsx
=> FIX/클라이언트 버그 수정#171

src/axios/BookingListApi.tsx, src/axios/HostTotalManagementAmountAPI.tsx, src/axios/ManagementRequestAPI.tsx, src/components/cards/CardOrderFix.tsx, src/components/cards/CardOrderWating.tsx, src/pages/host/HostMain.tsx, src/pages/host/Management.tsx, src/pages/host/hostCalender/HostCalendar.tsx, src/stores/useHostActionStore.tsx
=> FEAT: 호스트 예약관리 상태변경 기능 구현

src/App.tsx, src/assets/Dropdown.tsx, src/assets/Header.tsx, src/axios/roomApi.ts, src/axios/searchApi.ts, src/components/DetailInfo.tsx, src/components/Search.tsx, src/components/cards/CardAccommodations.tsx, src/components/cards/CardStateroom.tsx, src/customHooks/useDateDashFormet.tsx, src/pages/Main.tsx, src/pages/reservations/AccmoInfoCard.tsx, src/pages/reservations/ReservAccoCard.tsx, src/pages/reservations/ReservationCompleted.tsx, src/pages/reservations/index.tsx, src/pages/room/Accommodations.tsx, src/pages/search/Map.tsx, src/pages/search/index.tsx, src/stores/useAccommodationsStore.tsx, src/stores/useSearchRoomStore.tsx, src/stores/useSearchStore.tsx, src/stores/useStateroomStore.tsx
=> FEAT : 검색리스트

src/assets/Header.tsx, src/pages/search/Map.tsx
=> FIX:훅 위치 변경

src/assets/carousel/Carousel.tsx, src/axios/searchApi.ts, src/components/DetailInfo.tsx, src/components/Search.tsx, src/pages/room/Accommodations.tsx, src/pages/room/Stateroom.tsx, src/pages/search/Map.tsx, src/stores/useAccommodationsStore.tsx, src/stores/useStateroomStore.tsx
=> FEAT: 지도 이동 시 검색

.github/workflows/deploy.yml
=> TEST: workflows 테스트

src/pages/host/setAccommodations/EditMultiAccommodations.tsx, src/pages/host/setAccommodations/EditMultiRoom.tsx, src/pages/host/setAccommodations/EditOnlyRoom.tsx, src/pages/host/setAccommodations/HostDocuments.tsx, src/pages/host/setAccommodations/MultiAccommodations.tsx, src/pages/host/setAccommodations/MultiStaterRoom.tsx, src/pages/host/setAccommodations/OnlyAccommodation.tsx, src/pages/host/setAccommodations/OnlyStaterRoom.tsx, src/pages/host/setAccommodations/components/AccommodationInformation.tsx, src/pages/host/setAccommodations/components/AccommodationUse.tsx, src/pages/host/setAccommodations/components/AccommodationsPhoto.tsx, src/pages/host/setAccommodations/components/Documents.tsx, src/pages/host/setAccommodations/components/MultiRoomInformation.tsx, src/pages/host/setAccommodations/components/MultiRoomList.tsx, src/pages/host/setAccommodations/components/OnlyRoomInformation.tsx, src/pages/host/setAccommodations/components/RoomPhoto.tsx
=> FIX:병합충돌 오류수정

src/pages/reservations/CancelPopup.tsx, src/pages/reservations/ReservationCompleted.tsx
=> FEAT : 예약취소 정보

src/pages/host/setAccommodations/OnlyAccommodation.tsx
=> FIX: git 문제관련

src/App.tsx, src/axios/HostAccommodationAPI.tsx, src/pages/host/HostMain.tsx, src/pages/host/hostCalender/HostAccommoList.tsx, src/pages/host/hostCalender/HostCalendar.tsx
=> FEAT: 숙소수정 페이지 라우팅 연결

.github/workflows/deploy.yml, tsconfig.json
=> FEAT : workflow

.github/workflows/deploy.yml, src/pages/host/setAccommodations/HostDocuments.tsx
=> CHORE : workflow 수정

src/App.tsx, src/assets/Chips.tsx, src/pages/host/setAccommodations/StructureType.tsx, src/pages/user/EmailVerification.tsx, src/pages/user/SignUp.tsx
=> FIX:이메일인증,숙소유형선택/건물유형선택 UX/UI

src/pages/host/setAccommodations/SelectType.tsx, src/pages/host/setAccommodations/StructureType.tsx, src/pages/user/EmailVerification.tsx, src/pages/user/SignIn.tsx, src/pages/user/SignOut.tsx, src/pages/user/SignUp.tsx
=> REFACTOR: 코드 재확인

src/App.tsx, src/pages/user/SignIn.tsx
=> REFACTOR:코드리팩토링

src/assets/Header.tsx
=> FIX : 머지 해결

src/axios/userApi.ts, src/components/cards/CardStateroom.tsx, src/pages/reservations/ReservationCompleted.tsx, src/pages/room/Orders.tsx, src/pages/room/Stateroom.tsx, src/pages/user/MembershipWithdrawal.tsx, src/pages/user/SignIn.tsx, src/pages/user/SignUp.tsx, src/stores/useAuthStore.tsx
=> FEAT : 예약 시 유저 정보
